#server:
#  port: 8084
#spring:
#  application:
#    name: client

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka
#    registry-fetch-interval-seconds: 5
server:
  port: 8086

spring:
  application:
    name: eureka-client-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # one eureka server
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/ # two eureka server
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/ # three eureka server

    eureka-service-url-poll-interval-seconds: 5