server:
  port: 18081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: limit_test
          uri: lb://client
          predicates:
            - Path=/limit/**
          filters:
#            - RewritePath=/limit, /hello
            - StripPrefix=1
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
#                key-resolver: "#{@ipKeyResolver}"
#        - id: host_route
#          uri: http://127.0.0.1:8081
#          predicates:
#            - Path=/app/**
#          filters:
##            - StripPrefix=1
##            - PrefixPath=/world/
#            - RewritePath=/app/(?<segment>.*), /world/$\{segment}
#        - id: host_route
#          uri: lb://client
#          predicates:
#            - Path=/api/**
#          filters:
#            - StripPrefix=1

gate:
  client:
    world: http://127.0.0.1:8081
    hello: lb://client
eureka:
  client:
    register-with-eureka: true
    eureka.client.fetch-registry: true
    eureka.client.region: region-east
  service-url:
    zone1: http://localhost:8761/eureka,http://localhost:8762/eureka
    zone2: http://localhost:8763/eureka,http://localhost:8764/eureka
  availability-zones:
    region-east: zone1,zone2

logging: ## Spring Cloud Gateway的日志配置
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false